production:
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
        
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
        
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
        
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
        
  options:
    raise_not_found_error: false

development:
  sessions:
    default:
      database: feed_webservice_dev
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
        
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
        
  options:
    raise_not_found_error: false


test:
  sessions:
    default:
      database: feed_webservice_test
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
        
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
        
  options:
    raise_not_found_error: false